analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "test/**"
  
  # Disable all errors and warnings
  errors:
    deprecated_member_use: ignore
    lines_longer_than_80_chars: ignore
    directives_ordering: ignore
    prefer_const_constructors: ignore
    sort_constructors_first: ignore
    undefined_class: ignore
    undefined_method: ignore
    undefined_getter: ignore
    undefined_identifier: ignore
    missing_required_argument: ignore
    undefined_named_parameter: ignore
    argument_type_not_assignable: ignore
    return_of_invalid_type_from_closure: ignore
    non_type_as_type_argument: ignore
    unchecked_use_of_nullable_value: ignore
    creation_with_non_type: ignore
    const_with_non_const: ignore
    const_eval_property_access: ignore
    uri_does_not_exist: ignore
    non_bool_condition: ignore
    unrecognized_error_code: ignore

# Disable linter completely
linter: null